name: Run TenderScanner.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 8 AM UTC

env:
  sender_email: ${{ secrets.SENDER_EMAIL }}
  sender_pass: ${{ secrets.SENDER_PASS }}
  group_email: ${{ secrets.GROUP_EMAIL }}

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set file permissions
      run: chmod 666 PelitaCounter.txt

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract OCR
      run: brew install tesseract

    - name: Install Chrome and ChromeDriver
      run: |
        brew install --cask google-chrome
        brew install --cask chromedriver

    - name: Run TenderScanner
      run: python TenderScanner.py

    - name: Commit and push updated PelitaCounter.txt
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if git diff --exit-code PelitaCounter.txt > /dev/null; then
          echo "No changes in PelitaCounter.txt, skipping commit."
        else
          git add PelitaCounter.txt
          git commit -m "Update PelitaCounter.txt"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
