name: Run TenderScanner.py

on:
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 8 AM UTC

env:
  sender_email: ${{ secrets.SENDER_EMAIL }}
  sender_pass: ${{ secrets.SENDER_PASS }}
  group_email: ${{ secrets.GROUP_EMAIL }}

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.6'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract OCR
      run: brew install tesseract

    - name: Run TenderScanner
      run: |
        python TenderScanner.py

    - name: Install Chrome and ChromeDriver
      run: |
        brew install --cask google-chrome
        brew install chromedriver

    - name: Run TenderScanner
      run: python TenderScanner.py
      
